adminPassword: "admin"

service:
  type: LoadBalancer

persistence:
  enabled: true

env:
  GF_SERVER_ROOT_URL: "/grafana"
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Postgres
        uid: DS_POSTGRES
        type: postgres
        access: proxy
        url: 25.8.172.192:5432
        database: postgres
        user: postgres
        secureJsonData:
          password: postgres
        isDefault: true
        jsonData:
          sslmode: disable
          postgresVersion: 1200
          timeInterval: 1s

      - name: Postgres_records
        uid: DS_POSTGRES_records
        type: postgres
        access: proxy
        url: 25.8.172.192:5432
        database: records
        user: postgres
        secureJsonData:
          password: postgres
        isDefault: false
        jsonData:
          sslmode: disable
          postgresVersion: 1200
          timeInterval: 1s
      
      - name: Postgres_ratings
        uid: DS_POSTGRES_ratings
        type: postgres
        access: proxy
        url: 25.8.172.192:5432
        database: ratings
        user: postgres
        secureJsonData:
          password: postgres
        isDefault: false
        jsonData:
          sslmode: disable
          postgresVersion: 1200
          timeInterval: 1s

      - name: Loki
        uid: DS_LOKI
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false

      - name: Tempo
        uid: DS_TEMPO
        type: tempo
        access: proxy
        url: http://tempo:3200
        isDefault: false
        
      - name: Prometheus
        uid: DS_PROMETHEUS
        type: prometheus
        access: proxy
        url: http://prometheus:9090/prometheus
        isDefault: false

# единый блок sidecar — здесь оба под‐блока
sidecar:
  datasources:
    enabled: true
    intervalSeconds: 30

  dashboards:
    enabled: true           # Включаем поиск дашбордов
    label: grafana_dashboard  # Метка, по которой sidecar будет их подлавливать
    folder: /var/lib/grafana/dashboards  # Папка в контейнере Grafana
